# Automated Testing and Optimization
name: Test and Optimize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  # Performance testing
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://${{ github.repository_owner }}.github.io/github-guide-webpage/
          uploadArtifacts: true
          temporaryPublicStorage: true
          
  # Accessibility testing
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Pa11y
        run: npm install -g pa11y
        
      - name: Run accessibility tests
        run: |
          pa11y ./github-guide.html --reporter cli || true
          
  # Image optimization
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Optimize images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          
  # Bundle size check
  size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check file sizes
        run: |
          echo "File sizes:"
          find . -name "*.html" -o -name "*.css" -o -name "*.js" | xargs ls -lh
          
      - name: Total size
        run: |
          echo "Total project size:"
          du -sh .
          
  # Spell check
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Spell check
        uses: streetsidesoftware/cspell-action@v5
        with:
          files: "**/*.{html,md,js}"
          quiet: true